### ISSUE TITLE
Auto-Generate snatch.json file

### ISSUE THREAD

**Issue by emaadali** [JoyceStick-BC/Trimm-CLI#4]
After a bundle is downloaded, add the bundle name to a autogenerated file. Suggested syntax:

```json
{
    "assets": {
        "user1/asset1": versionNumber,
        "user2/asset2": versionNumber
    },
    "packages": {
        "user1/package1": versionNumber
    }
}
```

Does that work for you @CoolDude53?

**Comment by CoolDude53** [comment]
@emaadali 

With how it works now, when you install a bundle, it will come with a info.json file. The CLI will only touch this when pulling to:

1. to see if there are any version changes for any of it's bundles and when 
2. to see if there are any new bundles that aren't presently downloaded

If you need me to generate the info.json when a bundle is installed, we'll need to discuss how you will send me the info.

**Comment by CoolDude53** [comment]
I believe since we are doing both assets and packages, when the CLI makes an api request, it won't know whether its pulling an asset of a package, so what we planned on was for the api to return a zip file with a info.json that also the asset(s) zip files, that way whether its just one asset or a bunch of assets in a package, the CLI can handle all bundles the same.

**Comment by emaadali** [comment]
This is the format that the `snatch.json` file is supposed to look like (what you mistakenly called `info.json`). I will fix it at this point @CoolDude53.

**Comment by CoolDude53** [comment]
Yes, was unclear about the distinction between the two

**Comment by CoolDude53** [comment]
Handled with last commit.
